[package]
name = "hasher"
version = "0.1.0"
authors = ["Marcelo Lima <marcelowind@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
clap = "2"
digest = "0.8"
md-5 = "0.8"
num_cpus = "1.0"
sha2 = "0.8"
# ocl = "0.19"

[dependencies.eytzinger]
version = "1.0"
features = ["branchless"]
