name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Prepare OpenCL
      run: |
        sudo apt-get update
        sudo apt-get install -y clinfo mesa-opencl-icd
        sudo ln -s /usr/lib/x86_64-linux-gnu/libOpenCL.so.1 /usr/lib/libOpenCL.so
    - name: Prepare Cargo
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: clippy, rustfmt
        override: true
    - name: Format
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --verbose --workspace --all-features --all-targets
    - name: Lint
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --verbose --workspace --all-features --all-targets
    - name: Test
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --verbose --workspace --all-features --all-targets --no-fail-fast -- --nocapture
