name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Prepare OpenCL
        run: |
          sudo apt-get update
          sudo apt-get install -y clinfo mesa-opencl-icd
          sudo ln -s /usr/lib/x86_64-linux-gnu/libOpenCL.so.1 /usr/lib/libOpenCL.so
      - name: Prepare Cargo
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy, rustfmt
          override: true
      - name: Prepare QT
        uses: jurplel/install-qt-action@v2
        version: '6.1.1'
      - name: Format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose --workspace --all-targets --all-features
      - name: Build examples
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose --workspace --examples
      - name: Lint
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --verbose --workspace --all-targets --all-features
      - name: Lint examples
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --verbose --workspace --examples
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose --workspace --all-targets --all-features --no-fail-fast -- --nocapture
